server:
  port: ${PORT:8080}

spring:
  datasource:
    url: postgresql://guna:PyAeMVhZ4aH38jNe7ZZFOvyAnBKhJuZw@dpg-d75ma66uk2gs73dbs4b0-a/loka_database_plza
    username: guna
    password: PyAeMVhZ4aH38jNe7ZZFOvyAnBKhJuZw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
